services:
  - type: web
    name: pmlab-backend
    runtime: node
    plan: free # Can be changed to starter for 24/7 uptime
    region: frankfurt # Or any region close to you
    buildCommand: cd backend && npm install --include=dev && npx prisma generate && npm run build
    startCommand: cd backend && npm run start:prod
    envVars:
#      - key: NODE_ENV
#        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false # You will enter this in Render dashboard for security
      - key: JWT_SECRET
        generateValue: true # Render will generate a random secret for you
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
